### ISSUE TITLE
Decouple Pulsar Spring Boot auto-configuration components

### ISSUE THREAD

**Issue by sobychacko** [spring-projects-experimental/spring-pulsar#1]
Currently, we provide Spring Boot autoconfiguration as part of the core project [here](https://github.com/spring-projects-experimental/spring-pulsar/tree/main/spring-pulsar/src/main/java/org/springframework/pulsar/autoconfig). We need to decouple this into a separate module.

**Comment by migroskub** [comment]
One thing to consider is how to manage the `PulsarProperties` alongside `ReactivePulsarProperties` that will probably get implemented in the near future. Maybe there's should be some `CommonPulsarProperties`. This should get decided when thinking of the user's `application.properties`.

**Comment by onobc** [comment]
That is a good point @migroskub and definitely something we will consider up front. Coincidentally we are currently having to do a similar exercise for Reactive support in `spring-kafka`. Your forward thinking wrt Reactive counterpart in here is greatly appreciated.

**Comment by sobychacko** [comment]
The initial move is now complete. Closing the issue. Feel free to create more issues based on the above suggestions or as needs arise.
