### ISSUE TITLE
Consider making the class names consistent without the Pulsar prefix

### ISSUE THREAD

**Issue by sobychacko** [spring-projects-experimental/spring-pulsar#101]
Do we need to prefix all of these impls w/ `Pulsar`? It helps for example w/ `PulsarConsumerXYZ` as consumer is highly overloaded. But for others, not so much. Something to look at in general. 

I guess some consistent rule to use would be helpful across the project as a whole.

_Originally posted by @onobc in https://github.com/spring-projects-experimental/spring-pulsar/pull/100#discussion_r967571397_

**Comment by onobc** [comment]
@sobychacko taking another pass through all of the classes, I don't see anything sticking out that seems out of place. Let's call this one good.
