### ISSUE TITLE
Consider using Duration / DataSize where applicable

### ISSUE THREAD

**Issue by onobc** [spring-projects-experimental/spring-pulsar#119]
We are somewhat inconsistent w/ some of our data size and duration based properties. In some cases we do not name the var such that the unit can be determined. In some cases we name it w/ unit suffix of `ms` and in some `millis`. 

Lets scan through all of our properties and make this consistent. 
- PulsarProperties
- PulsarContainerProperties
- ???

_Originally posted by @onobc in https://github.com/spring-projects-experimental/spring-pulsar/pull/118#discussion_r972580211_

**Comment by cbornet** [comment]
I will use Duration for the reactive API.

**Comment by onobc** [comment]
Lets call this one closed via https://github.com/spring-projects-experimental/spring-pulsar/commit/b4203bedc8dc2f7bd2783231f12a906a0bf5710b
