### ISSUE TITLE
Spring Boot 3.0.0 RC-1

### ISSUE THREAD

**Issue by tspannhw** [spring-projects-experimental/spring-pulsar#177]
is that ready to test?

**Comment by onobc** [comment]
We are currently still on snapshots (SB 3.0.0-SNAPSHOT) which is effectively RC1 + 1 days of commits. However, it may be a good thing to hop onto the RC train now that it is available. Will discuss w/ team and figure out when to do this.

Thanks for creating the issue @tspannhw .

**Comment by sobychacko** [comment]
@tspannhw I quickly updated a standalone app to Boot RC1 now and that seems to be working fine.

**Comment by tspannhw** [comment]
I updated my pom.xml to RC1 from M4 and no changes were noticed.   I will keep an eye on tests and runs.

**Comment by cbornet** [comment]
Spring Boot 3 has been released: https://github.com/spring-projects/spring-boot/releases/tag/v3.0.0

**Comment by onobc** [comment]
Main is now locked onto SB `3.0.0`.
