### ISSUE TITLE
Partitioned Topics Work Once, Fail Subsequently

### ISSUE THREAD

**Issue by rfecher** [spring-projects-experimental/spring-pulsar#266]
The createIfExists logic for partitioned topics will work the first time if it doesn't exist but subsequent times when it does exist it will fail.  I debugged the logic and topic names do not have `-parition-` in them as expected by this logic:
https://github.com/spring-projects-experimental/spring-pulsar/blob/main/spring-pulsar/src/main/java/org/springframework/pulsar/core/PulsarAdministration.java#L146

Therefore it thinks the topic doesn't exist when it in fact does and it will try to create it and fail.

**Comment by onobc** [comment]
Thanks for the report @rfecher.

Do you mind including some simple repro steps?

**Comment by onobc** [comment]
@rfecher I wonder if the partition naming is configurable because I see the topic names w/ the `-partiion-` in the name. Can you share some info on your setup and how to reproduce this? Thanks.


<img width="700" alt="Screen Shot 2023-01-05 at 21 22 55" src="https://user-images.githubusercontent.com/28907971/210923912-90f1211b-3660-4689-8767-72048ab2ae9c.png">

**Comment by rfecher** [comment]
I'm just using `org.springframework.pulsar:spring-pulsar-spring-boot-starter:0.1.0-SNAPSHOT` for trying to create the partitioned topics per the guidelines and running the pulsar docker standalone image: apachepulsar/pulsar:2.10.0 
I'm also just using `public/default` for the tenant and namespace.

**Comment by onobc** [comment]
@rfecher is the stacktrace you are seeing something like:

> 
> java.lang.RuntimeException: org.apache.pulsar.client.admin.PulsarAdminException$ConflictException: This topic already exists
> 	at org.springframework.pulsar.core.PulsarAdministration.lambda$doCreateOrModifyTopicsIfNeeded$4(PulsarAdministration.java:212) ~[main/:na]
> 	at java.base/java.util.HashMap.forEach(HashMap.java:1421) ~[na:na]
> 	at org.springframework.pulsar.core.PulsarAdministration.doCreateOrModifyTopicsIfNeeded(PulsarAdministration.java:166) ~[main/:na]
> 	at org.springframework.pulsar.core.PulsarAdministration.createOrModifyTopicsIfNeeded(PulsarAdministration.java:156) ~[main/:na]
> 	at org.springframework.pulsar.core.PulsarAdministration.initialize(PulsarAdministration.java:125) ~[main/:na]

Also, did the topic already exist w/ no partitions and then one was added w/ partitions? For example...

**Time 0**
```java
@Bean
PulsarTopic pulsarTopic() {
   return PulsarTopic.builder("bar").numberOfPartitions(0).build();
}
```
That will create a topic named `"persistent://public/default/bar"`.

**Time 1**
```java
@Bean
PulsarTopic pulsarTopic() {
  return PulsarTopic.builder("bar").numberOfPartitions(3).build();
}
```
This fails w/ the above exception.
