### ISSUE TITLE
Pulsar Reader Support

### ISSUE THREAD

**Issue by rfecher** [spring-projects-experimental/spring-pulsar#273]
I'd like to use the topic retention policy along with a "Reader" client (https://pulsar.apache.org/docs/2.10.x/concepts-clients/#reader-interface) to be able to retrieve all retained messages on initialization of the consumer service, even those that have been acknowledged.  It doesn't appear that there is any means to do this in the current spring-pulsar client interfaces?

**Comment by onobc** [comment]
Hi @rfecher ,

There is currently no support for the regular (imperative client) reader yet. We will try to get to this soon though.

However, there is a Reactive reader that is auto-configured (see https://docs.spring.io/spring-pulsar/docs/current-SNAPSHOT/reference/html/#reactive-pulsar-reader).

**Comment by rfecher** [comment]
thanks for the quick response @onobc!

**Comment by onobc** [comment]
Closing via 
- https://github.com/spring-projects-experimental/spring-pulsar/issues/328
- https://github.com/spring-projects-experimental/spring-pulsar/commit/8dd39fdc7add5b6ae75f53e2a47eaeeaaa355408

**Comment by onobc** [comment]
@rfecher first wave of the imperative support has been added w/:
* auto-configured `PulsarReaderFactory`
* config props for the reader factory (`spring.pulsar.reader.*`)

Docs will be here shortly https://docs.spring.io/spring-pulsar/docs/current-SNAPSHOT/reference/html/#pulsar-reader
https://docs.spring.io/spring-pulsar/docs/current-SNAPSHOT/reference/html/#reactive-pulsar-reader

I believe we are planning on adding a `@PulsarReader` as well. Stay tuned. But you can grab a snapshot now and give it spin.
