### ISSUE TITLE
Pause/Resume improvements

### ISSUE THREAD

**Issue by sobychacko** [spring-projects-experimental/spring-pulsar#296]
I think it would be more consistent and easier to follow if we instead do pause/resume exactly how start/stop is currently implemented. This would also remove the need to attempt to use the lifecycleMonitor in the subclass. 

Basically, we would have an abstract `doPause()/doResume()` where the concurrent does the 1-N delegation call to its child containers and each child container then does the work to pause/resume (as you have it now).

_Originally posted by @onobc in https://github.com/spring-projects-experimental/spring-pulsar/pull/292#discussion_r1089827965_

**Comment by onobc** [comment]
Closed via https://github.com/spring-projects-experimental/spring-pulsar/commit/224eb0b3e2d9c2e1cb9466c2efda8f9dea851e24
