### ISSUE TITLE
Project Reactor support

### ISSUE THREAD

**Issue by rolkhas2** [spring-projects-experimental/spring-pulsar#31]
There are many users who'd like to use this, but cannot because this project is based on slow sync connections. I'd like to request to consider supporting Project Reactor \ async connections from the very start, so this project will be usable for many of us.

For those who'll find this issue useful, I recommend using the great [reactive-pulsar](https://github.com/datastax/reactive-pulsar) meanwhile.

**Comment by onobc** [comment]
We already are discussing this https://github.com/spring-projects-experimental/spring-pulsar/issues/7

**Comment by sobychacko** [comment]
@rolkhas2 Thanks for your interest in the project. As @onobc suggested, at the moment, we are focussing on ensuring that the foundations are laid properly. However, do you mind elaborating on the slow sync connections you mentioned? At the moment, Spring Pulsar clients are using the `PulsarClient` provided by the Java client in Pulsar. Is that you were referring to? When you respond, feel free to comment on the other [open issue](https://github.com/spring-projects-experimental/spring-pulsar/issues/7).

**Comment by lynch19** [comment]
Are there any plans for reactive spring pulsar implementation?

**Comment by sobychacko** [comment]
@lynch19 We are looking into this area of reactive use cases in general. In a few weeks, we hope to update you on this issue.
