### ISSUE TITLE
SchemaResolver default to Schema.JSON

### ISSUE THREAD

**Issue by cbornet** [spring-projects-experimental/spring-pulsar#323]
For discussion.
Currently, if the Schema is not specified and there is no custom schema mapping, the schema resolver defaults to BYTES.
It could be interesting to default to JSON instead using Schema.JSON(messageType).

**Comment by onobc** [comment]
Yeh, I had this same thought a while back - glad you brought it back up @cbornet . It does seem like the common case that **IF** we have the message type (and its not primitive type) t is a good bet to go w/ JSON. We can default to `BYTES` when we do not have a message type.

**Comment by cbornet** [comment]
Yes. Currently we set BYTES burt then get ClassCastException : see https://github.com/spring-projects-experimental/spring-pulsar/pull/324/files#diff-8f7a82c407cdc7c29bd06ca7e4ebd9dd6e9cdd1adb18a8b2b5cc9d6ce2549761R278
With this it would work better.
