### ISSUE TITLE
Provide the ability to set ProducerInterceptors on PulsarTemplate

### ISSUE THREAD

**Issue by sobychacko** [spring-projects-experimental/spring-pulsar#35]
Consider adding the producer interceptor[s] on the Pulsar producer factory through `PulsarTemplate`.  When the producer is created in the factory, the interceptor[s] are passed on to the producer.

**Comment by alpreu** [comment]
I'd like to have a go at this, you can assign the ticket to me :)

**Comment by onobc** [comment]
There is the consumer [counterpart](https://github.com/spring-projects-experimental/spring-pulsar/issues/36) as well. I am not sure if there is any overlap etc.. but it would be good to keep that in mind when design/impl etc..
