### ISSUE TITLE
[Build] Gradle 8 Not Supported

### ISSUE THREAD

**Issue by tspannhw** [spring-projects-experimental/spring-pulsar#51]
spring-pulsar % ./gradlew build

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.1/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by onobc** [comment]
Thanks for the report @tspannhw . I will take a look at those deprecations and adjust. While we build w/ 7.4.1 it is a good idea to cleanup these deprecations early on. I am currently in the process of cleaning the build up so this is good timing.

**Comment by onobc** [comment]
@tspannhw I just wanted to give an update on this... I did a 1st round of build rework but did not get the deprecated pieces removed *yet*. The scope creeped on me and things took longer than expected. Therefore, I am going to do a 2nd round of refactors in the upcoming weeks and will include this in that effort. Just wanted to let you know we are not disregarding your request.

**Comment by onobc** [comment]
We are going to close this for now and when we add support for Gradle 8 we will create another issue. Right now we will require Gradle 7.
