### ISSUE TITLE
Get spring-pulsar on start.spring.io

### ISSUE THREAD

**Issue by onobc** [spring-projects-experimental/spring-pulsar#69]
This work is covered here https://github.com/spring-io/start.spring.io/issues/987 but will keep this ticket to track progress and link to M1.

**Comment by onobc** [comment]
I have this working locally w/ the follwing support: 
- pulsar starter
- pulsar reactive starter
- pulsar SCSt binder
- pulsar testcontainer support

See https://github.com/onobc/start.spring.io/tree/cbono-add-spring-pulsar-gh-987

**Comment by onobc** [comment]
Closing in favor of https://github.com/onobc/start.spring.io/tree/cbono-add-spring-pulsar-gh-987

**Comment by eddumelendez** [comment]
Just adding a link to the [PR](https://github.com/spring-io/start.spring.io/pull/1136)
