### ISSUE TITLE
Reactive Spring Pulsar Explanations

### ISSUE THREAD

**Issue by migroskub** [spring-projects-experimental/spring-pulsar#7]
I’d like to understand how exactly does the `reactive-spring-pulsar` integration will work.

The great [spring-pulsar community project](https://github.com/majusko/pulsar-java-spring-boot-starter) supports the project Reactor very well, and I’d like to know how that’s have been implemented here, and how to usage exactly looks.

Reactor and Pulsar integration with Spring is super needed and lots of people are waiting for this a long time (and for the Spring-Pulsar in general). I’ve been super disappointed to not seeing **any** reference for the reactive usage in the `README.md`. I think this one should be well documented, so people will easily be able to help with initial features.

I think that in general this project can lookup for lots of references from the reactor-kafka and reactor-rabbitmq projects.

**Comment by sobychacko** [comment]
@migroskub Thank you for creating the issue. This project is very new and in its early phases. The goal of this project is to provide Spring friendly Pulsar abstractions with the same design philosophies of [Spring for Apache Kafka](https://github.com/spring-projects/spring-kafka). At the moment, on the producing side, we provide a template for publishing and the necessary producer factory APIs. On the consumer side, there is a `PulsarListener` annotation which is backed by the message listener container pattern. We are working to provide a detailed README for the usage patterns on these.

We are trying to get the foundational elements in place first before tackling the reactive components. Thus, there is no reactive support in this yet, but eventually, once things stabilize, we can follow the same approach in reactor-kafka project to implement reactive solutions here. However, we are all ears for any suggestions and PR contributions for this specific feature or any other features relating to this library. Thank you once again!

**Comment by migroskub** [comment]
@sobychacko I'd suggest to support Reactor from the very first phase. That's because more users will be able to use the most simple case from the very first release.
I also wonder why don't we implement this in a fully Reactor way, and users who might don't want to use the non-blocking async API will use `.block()`? This way we won't need to implement stuff twice

**Comment by lhotari** [comment]
There's also a Reactive Streams (Project Reactor) adapter for Pulsar Java Client implemented in https://github.com/datastax/reactive-pulsar . It also solves the async non-blocking backpressure challenge for producers and supports pipelining usecases for configurable parallelism levels. I'm happy to share more details of the how this is achieved. 
By default, Pulsar Java client will either overflow or block for backpressure when a producer is producing faster than the broke can receive messages. When using Reactive, one of the main reasons is to be able to use async non-blocking backpressure.

**Comment by lynch19** [comment]
Can the current spring pulsar async endpoints work with reactor code?

**Comment by sobychacko** [comment]
@lynch19 I think the reactor-based implementation mentioned above uses the async send API. We can also probably use that model as a starting point.

**Comment by migroskub** [comment]
@sobychacko can you further explain? Is there an async endpoint on the current Spring Pulsar version?
And btw, when is the Reactive Spring Pulsar’s implementation expected?

**Comment by code-magician323** [comment]
When is this going to get implemented?

**Comment by migroskub** [comment]
The new official reactive pulsar client (e.g. https://github.com/apache/pulsar-client-reactive) is relevant for this discussion. @lhotari as the author, can you explain a little about this new client? Is this a migration of the [reactive-pulsar](https://github.com/datastax/reactive-pulsar) repo? Or are there some differences we need to know?
I've seen that there is no Spring reference in the new client.

**Comment by onobc** [comment]
@migroskub @sobychacko @lhotari I created a [Github Discussion](https://github.com/spring-projects-experimental/spring-pulsar/discussions/99) to discuss all things Reactive support in Spring Pulsar. Currently this info is scattered about several issues so maybe moving to the discussion would centralize things and make it more of a discussion.
