### ISSUE TITLE
Maven Based Separate Sample Application

### ISSUE THREAD

**Issue by tspannhw** [spring-projects-experimental/spring-pulsar#84]
It would be helpful to have a standalone repository with a simple maven example

**Comment by sobychacko** [comment]
@tspannhw That is a great idea. We can certainly look into that. In the meantime, did you get to look at these [samples](https://github.com/spring-projects-experimental/spring-pulsar/blob/main/spring-pulsar-sample-apps/README.adoc)?

**Comment by onobc** [comment]
@tspannhw we have been moving recently toward the trend of keeping samples in the same repo as the main project. This pattern of keeping them close to the code seems to help keep them up-to-date and avoid bit rot. I would prefer to not maintain a separate repo for this.

As @sobychacko pointed out we do have a couple of examples in this repo. However, I just realized that we can not simply point users to those samples as they do have some of our custom Gradle plugins in the `build.gradle`. 

Wdyt about us adding some directions on "Getting started" section of the ref docs (could show a tabbed pane for Gradle / Maven) to help w/ this gap? 

Also, we are in the process of making `spring-pulsar` available on [start.spring.io](https://github.com/spring-projects-experimental/spring-pulsar/issues/69) which will give users a simple way to get started w/ a SpringBoot app.

**Comment by onobc** [comment]
We updated the ref docs to clearly show how to get started w/ gradle or maven. Based on this and the fact that we will be on start.spring.io in the near future I will close this out.
