### ISSUE TITLE
Spring boot 2.7.x support

### ISSUE THREAD

**Issue by austek** [spring-projects-experimental/spring-pulsar#94]
Spring boot v2.7.x is supported for the same period of time as the v3.x. As v2.7.x is still in use `spring-pulsar` should provide support for it.

**Comment by onobc** [comment]
This is not something that we are planning on supporting @austek.

**Comment by sobychacko** [comment]
@onobc It would be nice to find out the gap if any users want the framework to run against Boot 2.7. I guess since we bring some hard dependencies at compile time (Boot 3/SF 6/Java 17 etc), that itself could be a problem for end users. 

@austek What are the immediate issues you found out when trying to do this?

**Comment by onobc** [comment]
> I guess since we bring some hard dependencies at compile time (Boot 3/SF 6/Java 17 etc), that itself could be a problem for end users.

Yeh, for the SB3/SF6 dependencies we could handle that w/ exclusions/overrides etc.. The Java 17 requirement is the one that could introduce challenges as I am sure we are using its features in the codebase (which has been really nice not being anchored to the lowest common denominator).

**Comment by austek** [comment]
> @austek What are the immediate issues you found out when trying to do this?


> Yeh, for the SB3/SF6 dependencies we could handle that w/ exclusions/overrides etc.. The Java 17 requirement is the one that could introduce challenges as I am sure we are using its features in the codebase (which has been really nice not being anchored to the lowest common denominator).

I've tried to use `(Boot 2.7.3/SF 5.3.22/Java 11)`, had to change switch statements and one multiMap so far, now trying to fix some tests

**Comment by austek** [comment]
I've managed get `(Boot 2.7.3/SF 5.3.22/Java 11)` to compile and pass tests

https://github.com/austek/spring-pulsar/tree/use_jdk_11

**Comment by austek** [comment]
@onobc What do you think of supporting above configuration that I've tried with, should I raise a full PR?

**Comment by sobychacko** [comment]
@austek Sorry for not getting back to you earlier; we were busy getting the M1 out. A significant issue with the approach you proposed in the fork is the downgrading of the JDK to 11. For Spring Pulsar, we would like to maintain a minimum baseline of Java 17. But we are certainly open to ideas and would like to find a path for your use cases. Do you have a situation where you cannot upgrade from Boot 2.x to 3.0 in the near future?

**Comment by austek** [comment]
Unfortunately, we're stuck on Boot 2.x and Java 11 world for now and don't see upgrading soon

**Comment by austek** [comment]
is it possible to setup a meeting too discuss possibilities?

**Comment by sobychacko** [comment]
@austek Sure, we are open to a meeting to discuss this. Please email your availability, and we can set up a meeting. 

cc @onobc

**Comment by onobc** [comment]
Based on recent discussions we will not be moving forward w/ SB 2.7 support. Thank you @austek for all your work towards this.
