### ISSUE TITLE
Using Pulsar with Reactor core

### ISSUE THREAD

**Issue by code-magician323** [spring-projects-experimental/spring-pulsar#98]
I'd like to know if it is possible to use spring pulsar with reactor core. I've seen that there is a `.sendAsync()` method so I guess there is some workaround for making this integration work. Can someone help with this?

**Comment by migroskub** [comment]
Seems like [the pulsar official reactive client](https://github.com/apache/pulsar-client-reactive) would help. The only thing that's left is the connection between the reactive client and spring-pulsar

**Comment by onobc** [comment]
Lets move this to the newly created GH discussion https://github.com/spring-projects-experimental/spring-pulsar/discussions/99.
